version: "3"

services:
  postgres:
    image: 'postgres:9.6.11-alpine'
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build: .
    command: bundle exec rails s -p 3000 -b "0.0.0.0"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - '.env'
    depends_on:
      - postgres
      - webpack

  webpack:
    build: .
    command: ./bin/webpack-dev-server --inline true
    env_file:
      - '.env'
    volumes:
      - ".:/app"
    ports:
      - "3035:3035"

volumes:
  web:
  postgres:
  webpack:
